grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      
      n_estimators: 500
      max_depth: 7
      learning_rate: 0.1
    search_param_grid:
      n_estimators: 
      - 100 
      - 300
      - 500 # Number of boosting rounds
      learning_rate:
      - 0.01
      - 0.1
      - 0.2
      - 0.3  # Shrinks contribution of trees
      max_depth:
      - 3
      - 5
      - 7
      - 10  # Tree depth (higher = risk of overfitting)
   
  module_1:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      max_depth: 10
      max_features: log2
      n_estimators: 500
    search_param_grid:
      max_depth:
      - 10
      - 15
      - 20
      
      max_features:
      - sqrt
      - log2
      n_estimators:
      - 100
      - 50
      - 200
      - 500    
      